// src/lib/components/Navbar.svelte
<nav>
  <div class="nav">
      <div class="logo">
          <a href="#home">NDS</a>
      </div>
      <ul class="nav-links">
          <li><a href="#home">Home</a></li>
          <li><a href="#orari">Orari</a></li>
          <li><a href="#contatti">Contatti</a></li>
          <li><a href="#carita">Carità</a></li>
          <li><a href="#attivita">Attività</a></li>
          <li><a href="#oratorio">Oratorio</a></li>
          <li><a href="#catechismo">Catechismo</a></li>
          <li><a href="#giovani">Giovani</a></li>
          <li><a href="#lachiesa">La chiesa</a></li>
          <li><a href="#storia">La storia</a></li>
          <li><a href="#preti">I preti</a></li>
          <li><a href="#cpp">CPP</a></li>
          <li><a href="#calendario">Calendario</a></li>
      </ul>
  </div>
</nav>

  
  <style>

  </style>

// src/components/Navbar/Navbar.jsx
import "./Navbar.css";

import { useEffect, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";

const navItems = [
	{ to: "/", label: "Home" },
	{ to: "/orari", label: "Orari" },
	{ to: "/contatti", label: "Contatti" },
	{ to: "/carita", label: "Carità" },
	{ to: "/attivita", label: "Attività" },
	{ to: "/oratorio", label: "Oratorio" },
	{ to: "/catechismo", label: "Catechismo" },
	{ to: "/giovani", label: "Giovani" },
	{ to: "/la-chiesa", label: "La chiesa" },
	{ to: "/la-storia", label: "La storia" },
	{ to: "/i-preti", label: "I preti" },
	{ to: "/cpp", label: "CPP" },
	{ to: "/calendario", label: "Calendario" },
];

function Navbar() {
	const [isOpen, setIsOpen] = useState(false);
	const location = useLocation();

	useEffect(() => {
		setIsOpen(false);
	}, [location.pathname]);

	return (
		<div className="nav-wrap">
			<div className="nav-topbar">
				<button
					type="button"
					className="menu-toggle"
					aria-label="Apri o chiudi il menu di navigazione"
					aria-expanded={isOpen}
					aria-controls="site-navigation"
					onClick={() => setIsOpen((open) => !open)}
				>
					<span />
					<span />
					<span />
				</button>
			</div>

			<nav id="site-navigation" className={`site-nav ${isOpen ? "is-open" : ""}`} aria-label="Navigazione principale">
				{navItems.map((item) => (
					<NavLink
						key={item.to}
						to={item.to}
						end={item.to === "/"}
						className={({ isActive }) => `nav-link${isActive ? " is-active" : ""}`}
					>
						{item.label}
					</NavLink>
				))}
			</nav>
		</div>
	);
}

export default Navbar;
