// src/lib/components/Footer.svelte
<script>
  	import { base } from '$app/paths';
</script>


<!-- src/lib/components/Footer.svelte -->
<footer class="footer">
  <div class="footer-container">

    <!-- Info Parrocchia -->
    <div class="footer-section">
      <h3>Parrocchia Natale del Signore</h3>
      <p>Via Boston 37, 10137 Torino</p>
      <p>Tel: <a href="tel:011352013">011.352013</a></p>
      <p>Email: <a href="mailto:parr.natale@diocesi.to.it">parr.natale@diocesi.to.it</a></p>
    </div>

    <!-- Altre Parrocchie -->
    <div class="footer-section">
      <h3>Le altre parrocchie dell'Unità Pastorale</h3>
      <ul>
        <li><a href="https://www.srita.it/">S. Rita</a></li>
        <li><a href="https://www.madonnarose.it/">Madonna delle Rose</a></li>
        <li><a href="https://www.parrocchie.it/torino/mariamadredellachiesa/">Maria Madre della Chiesa</a></li>
        <li><a href="https://www.madremisericordia.it/">Maria Madre di Misericordia</a></li>
      </ul>
    </div>

    <!-- Social -->
    <div class="footer-section">
      <h3>Seguici sui social</h3>
      <div class="social-icons">
        <a href="https://www.facebook.com/parrocchianatale.delsignore" target="_blank" rel="noopener noreferrer">
          <img src="{base}/social/Fb-logo.png" alt="Facebook">
        </a>
        <a href="https://www.instagram.com/parrocchiands/" target="_blank" rel="noopener noreferrer">
          <img src="{base}/social/IG-logo.png" alt="Instagram">
        </a>
      
        <!-- altri social -->
      </div>
    </div>

  </div>

  <div class="footer-bottom">
    &copy; {new Date().getFullYear()} Parrocchia Natale del Signore
  </div>
</footer>

<style>
.footer {
  background-color: #cce7f0; /* azzurro chiaro */
  padding: 3rem 1rem;
  color: #1a1a1a;
  font-family: sans-serif;
}

.footer-container {
  max-width: 1000px;
  margin: 0 auto;
  display: flex;
  flex-wrap: wrap;
  gap: 2rem;
}

.footer-section {
  flex: 1 1 250px;
}

.footer-section h3 {
  font-weight: bold;
  margin-bottom: 0.5rem;
  color: #007c91; /* un azzurro più scuro per i titoli */
}

.footer-section p,
.footer-section ul,
.footer-section a {
  margin: 0.3rem 0;
  color: #1a1a1a;
  text-decoration: none;
}

.footer-section ul {
  list-style: none;
  padding: 0;
}

.footer-section a:hover {
  text-decoration: underline;
  color: #005f6b;
}

.social-icons {
  display: flex;
  gap: 1rem;
  margin-top: 0.5rem;
}

.social-icons img {
  width: 30px;
  height: 30px;
  transition: transform 0.2s;
}

.social-icons img:hover {
  transform: scale(1.2);
}

.footer-bottom {
  text-align: center;
  margin-top: 2rem;
  font-size: 0.9rem;
  color: #004850; /* colore del testo leggermente più scuro */
}
</style>

// src/components/Footer/Footer.jsx
import "./Footer.css";

function Footer() {
	return (
		<footer className="site-footer">
			<div className="footer-col footer-col-logo" aria-hidden="true">
				<img
					src={`${import.meta.env.BASE_URL}img/logoNDS.png`}
					alt="Logo Parrocchia Natale del Signore"
					className="footer-logo"
				/>
			</div>

			<div className="footer-col">
				<h3>Parrocchia Natale del Signore</h3>
				<p>Via Boston 37, 10137 Torino</p>
				<p>Tel. 011.352013</p>
				<p>
					Email: <a href="mailto:parr.natale@diocesi.to.it">parr.natale@diocesi.to.it</a>
				</p>
			</div>

			<div className="footer-col">
				<h3>Unità Pastorale</h3>
				<p>
					<a href="http://www.srita.it/" target="_blank" rel="noreferrer">
						S. Rita
					</a>
				</p>
				<p>
					<a href="http://www.madonnadellerose.it" target="_blank" rel="noreferrer">
						Madonna delle Rose
					</a>
				</p>
				<p>
					<a href="http://www.parrocchie.it/torino/mariamadredellachiesa/" target="_blank" rel="noreferrer">
						Maria Madre della Chiesa
					</a>
				</p>
				<p>
					<a href="http://www.madremisericordia.it" target="_blank" rel="noreferrer">
						Maria Madre di Misericordia
					</a>
				</p>
			</div>

			<div className="footer-col footer-col-social">
				<h3>Seguici</h3>
				<a
					className="facebook-link"
					href="http://www.facebook.com/parrocchianatale.delsignore"
					target="_blank"
					rel="noreferrer"
					aria-label="Pagina Facebook Parrocchia Natale del Signore"
				>
					<span className="fb-icon" aria-hidden="true">
						f
					</span>
					Facebook
				</a>
			</div>
		</footer>
	);
}

export default Footer;
